inherit: true

build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
                before:
                    # a workaround for https://github.com/sebastianbergmann/phpunit/issues/1976
                    - stty cols 80
                    - curl -Ls http://get.sensiolabs.de/deptrac.phar > deptrac && chmod +x deptrac
                override:
                    - composer install
                after:
                    - php bin/console cache:warmup
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
            environment:
                hosts:
                    report.awin: '127.0.0.1'
                apache2:
                    modules: ['rewrite']
                    sites:
                        awin_report_ms:
                            web_root: 'web/'
                            host: 'report.awin'
                php:
                    version: '7.1'
                elasticsearch: false
                rabbitmq: false
                redis: false
                postgresql: false
                variables:
                    APP_ENV: test
        tests: true
    cache:
        directories:
            - ~/.composer/
    dependencies:
       before:
           - sudo apt-get install -y --force-yes graphviz
    tests:
        override:
            -
                command: './vendor/bin/phpunit --testsuite="unit" --coverage-clover=var/code-coverage/phpcov-unit.xml --printer PHPUnit_TextUI_ResultPrinter'
                coverage:
                    file: 'var/code-coverage/phpcov-unit.xml'
                    format: 'php-clover'
            -
                command: './vendor/bin/phpunit --testsuite="integration" --coverage-clover=var/code-coverage/phpcov-integration.xml --printer PHPUnit_TextUI_ResultPrinter'
                coverage:
                    file: 'var/code-coverage/phpcov-integration.xml'
                    format: 'php-clover'
            -
                command: 'php ./deptrac.phar analyze depfile.yml --formatter-graphviz-dump-image=/home/scrutinizer/artifacts/dependencies.png'


filter:
    excluded_paths:
            - 'app/*'
            - 'bin/*'
            - 'features/*'
            - 'tests/*'
            - 'varF/*'
            - 'vendor/*'

build_failure_conditions:
    - 'elements.rating(<= B).new.exists'
    - 'issues.label("coding-style").new.exists'
    - 'issues.severity(>= MAJOR).new.exists'

checks:
    php: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: false