services:
    api.controllers.v1.default:
        class: Awin\ReportTask\Bundle\ReportBundle\Controller\v1\DefaultController
        arguments: []
    api.controllers.v1.phone_number:
            class: Awin\ReportTask\Bundle\ReportBundle\Controller\v1\PhoneNumberController
            arguments: []